### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by tsalada** [masak/007#121]
$panda install 007
==> Fetching 007
==> Building 007
==> Testing 007
t/code-style/four-space-indent.t ............ ok
t/code-style/line-ending-ws.t ............... ok
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
grep: warning: recursive search of stdin

At this point, It must have been looping recursively as I didn't get a $ prompt back until after Control-C

**Comment by andreoss** [comment]
The tests depend on GNU Find, and it seems your system has some other version.

**Comment by masak** [comment]
* I'd be interested if someone could identify what version of `find` it is that does not recognize `-name`. What platform is that, @tsalada? OS X?
* Ok, so we rewrite, without the `find` command. We could pull in [`File::Find`](https://github.com/tadzik/File-Find/blob/master/lib/File/Find.pm) as a dependency, but that seems a bit heavy for just a casual use in the tests. We've cloned `JSON::Tiny` in the test suite becuase we needed something similar. Let's do the same here; copy-and-paste, and whittle down to exactly what we need in this case.

**Comment by masak** [comment]
Yep, that should fix it. (Will push up a regression test in a moment.)

@tsalada, could you please test again and see if it works for you now?

**Comment by tsalada** [comment]
I'm using Mac OSX 10.10.5.

I got much further this time but then,
# Failed test 'all .pm files in lib/ are declared in META.info'
# at t/integration/meta-info.t line 12
# expected: ''
#      got: '- lib//_007/Runtime/Builtins.pm
and
# Failed test 'all .pm files declared in META.info also exist in lib/'
# at t/integration/meta-info.t line 17
# expected: ''
#      got: '- lib/_007/Q.pm

**Comment by masak** [comment]
Oh, look at that, that's another instance of `find -name` in `t/integration/meta-info.t`.

Re-opening this issue.

**Comment by masak** [comment]
There; @tsalada, could you try again? I'm not 100% it was that simple, but I'm hoping it was.

**Comment by tsalada** [comment]
This time installation was successful. Thank you for fixing this issue. I look forward to using the module.
