### ISSUE TITLE
Just implement infix:<%> and infix:<%%> already

### ISSUE THREAD

**Issue by masak** [masak/007#132]
I just looked over the examples, and it maybe it's me being obsessed with modulo-related code examples &mdash; probably &mdash; but it would seem that all three of `euclid-gcd.007`, `fizzbuzz.007`, and `nicomachus.007` would benefit from having `infix:<%>` (and `infix:<%%>`) built into the language.

So,

- [x] Let's implement those.
- [x] Let's *not* implement `infix:</>` for now. I'm still bothered by the things described in [this comment](https://github.com/masak/007/issues/34#issuecomment-147200158).
- [x] There's the risk of a division by zero, even with `infix:<%>` and `infix:<%%>`. So we'll need a new 007-exception type, and we'll need tests that try catching it.
- [ ] After we have the operators, we should go back and make the examples prettier.

**Comment by masak** [comment]
> - [x] There's the risk of a division by zero, even with `infix:<%>` and `infix:<%%>`. So we'll need a new 007-exception type, and we'll need tests that try catching it.

Actually, I ended up just using the Perl 6 exception (`X::Numeric::DivideByZero`) for now. We can save the custom-exceptions work for some later time, when we do it across the board.

**Comment by vendethiel** [comment]
actual commits: b19d939c17e97f1d02ed45319215a67ce31a45f3...8c0bb8ed52
