### ISSUE TITLE
Should we really go with hygiene by default?

### ISSUE THREAD

**Issue by masak** [masak/007#161]
I don't like to open philosophical issues. They tend to stay open a long time, and there is not much satisfaction in finally closing them. But I figure we might need to discuss this.

I'm reading [the LoL book](https://www.amazon.com/Let-Over-Lambda-Doug-Hoyte/dp/1435712757/). It's written from a Common Lisp perspective, and loudly proclaims itself as being so. One point of pride that it keeps coming back to &mdash; and I'm trying to characterize this as justly/closely as I can &mdash; is:

* Hygiene should be opt-in (as in Common Lisp), not opt-out (as in Scheme)
* Even in Scheme, the language that has arguably pushed hygiene the farthest, there are numerous safety hatches to circumvent the hygiene
* The risks perceived in not having hygiene are real, as in, they can really mess up your program if you use them in a not-intended way &mdash; aka "unwanted capture"
* However, the same techniques can be used purposefully to make up the foundation of such things as anaphoric macros

This makes one think.

Forget 007 for a little bit. Why are Perl 6 macros hygienic? Because S06 says they are, quite clearly:

> Within a quasiquote, variable and function names resolve according
> to the lexical scope of the macro definition.

At a guess, Damian Conway is the main author of that sentence. My mental simulation of him has him making macros hygienic &mdash; I'm not as sure about Larry. :smile:

What if Perl 6 macros weren't hygienic by default? I'm not just asking out of impishness, but primarily because over the years I've collected use cases people have been bringing forth where macros would help. And you know what? They are most often about generating code. More than half of the time people's expectations are that the code generated reside in exact lexical scope they expand the macro into.

Let's make this glaringly concrete. People would expect this:

    macro inject-vardecl() {
        quasi { my x = "world"; }
    }

    my a = "hello";
    inject-vardecl();
    say(a ~ " " ~ x);

To result in the moral equivalent of this code:

    my a = "hello";
    my x = "world";
    say(a ~ " " ~ x);

And they would like something like this:

    macro myfn(name) {
        my ident = new Q::Identifier { name: name.value };
        quasi {
            sub {{{ident @ Q::Identifier}}}(a1, a2, a3) {
                # ...long, complicated, boring autogenerated code...
            }
         }
    }

    myfn("important_library_function_1");
    myfn("important_library_function_2");
    # ...
    myfn("important_library_function_100");

To expand into a hundred beautiful autogenerated function declarations for them.

Are we gaining anything from making macros hygienic? Or would making them unhygienic by default and providing a mechanism akin to gensyms help us serve the use cases people have brought forward so far for macros?

**Comment by vendethiel** [comment]
> Are we gaining anything from making macros hygienic? Or would making them unhygienic by default and providing a mechanism akin to gensyms help us serve the use cases people have brought forward so far for macros?

We keep the language consistent ("everything is lexical"), and make the macro construction error-free by default. It might however be better to have two distincts things (...)

> Even in Scheme, the language that has arguably pushed hygiene the farthest, there are numerous safety hatches to circumvent the hygiene

I'm strongly convinced Racket has pushed it further than Scheme.

**Comment by vendethiel** [comment]
WRT my "(...)":

The reason scheme and racket can "get away" so easily with having hygiene **and** useful macros is because of templates (I'm not sure you've seen to many of those, so feel free to ask for more/bigger examples if needed). 

I'm going to need to drop a reference to [Fear of Macros](http://www.greghendershott.com/fear-of-macros) (sorry to increase the burden by adding more and more to your reading list everytime, but I believe this one must be in there already) because it shows macros-generating-macros using scheme/racket features.

**Comment by masak** [comment]
"Fear of Macros" is on my reading list. I will consider it a part of my "get to know Racket better" effort, up next after LoL.

Right now I'm thinking about processing stages during the compile. That seems to be where many differences come from between Lisp and Perl 6, and where issues such as this one arise.

Lisp:

    source text --[read]--> Sexprs --[macroexpand]--> Sexprs

Perl 6:

    source text --[parse/lexical check/macroexpand]--> byte code

It looks to me like Perl 6 doesn't really have stages: just like it eschews the distinction between lexing and parsing, it doesn't distinguish between read and macroexpand. And checking whether a variable resolves lexically to a definition happens *as part of the parse*, not as a late step. I don't know enough about Common Lisp to know whether it has a lexical check, but if it does, it doesn't happen *before* macroexpansion (or anaphoric macros wouldn't work).

If Perl 6 allowed variables to slip through its fingers before everything was macroexpanded, and only then did lexical checking, macros could perhaps be a little bit more free and it would make more sense to talk about unhygiene-by-default. But I have a feeling that the tendency to want to check variables ASAP is fairly deeply-rooted in Perl 6... and so, in a way, many of the challenges we're facing are about how to get those liberal Lisp-y mechanisms to work on top of a substrate that's fairly strict and wants everything to check out lexically, always.

**Comment by vendethiel** [comment]
> just like it eschews the distinction between lexing and parsing, it doesn't distinguish between read and macroexpand

The same is true of (Common) Lisp, basically:

>  don't know enough about Common Lisp to know whether it has a lexical check, but if it does, it doesn't happen before macroexpansion (or anaphoric macros wouldn't work).

There can be no such thing in Common Lisp, because of reader macros.

```
(install-my-great-reader-macro)
my $a = 3;
print $a;
```

To know if this is a valid program, you need to execute it.

**Comment by masak** [comment]
Ok, that's reassuring. (Kind of.)

Still, isn't there some sense in which code is treated *as data* for a lot longer in the Lisp compilation pipeline? I don't know if that's a good way to phrase it, but that's what it feels like. Perl 6 seems to have a tendency to want to validate and construct the code out of the source text as soon as it possibly can.

**Comment by vendethiel** [comment]
Yeah, sure. It's all just `read` and `eval`.

**Comment by raiph** [comment]
Just read [Walter Bright](https://en.wikipedia.org/wiki/Walter_Bright), writing succinct reddit comments 3 years ago, [on D macros](https://www.reddit.com/r/programming/comments/10k9ao/why_i_think_rust_is_the_language_of_the_future/c6ehjcp), mentioning hygiene, hygiene by default, "use `{}`" to get hygiene, templates, etc. Thought it might be of interest.

**Comment by masak** [comment]
Thanks @vendethiel and @raiph for feedback. Closing this issue for now, since (pending my reading more about Racket and [Fear of Macros](http://www.greghendershott.com/fear-of-macros)) the simple answer to the question in the subject seems to be "yes".

**Comment by masak** [comment]
> Just read [creator of D](https://en.wikipedia.org/wiki/Walter_Bright), Walter Bright, writing succinct reddit comments 3 years ago, [on D macros](https://www.reddit.com/r/programming/comments/10k9ao/why_i_think_rust_is_the_language_of_the_future/c6ehjcp), mentioning hygiene, hygiene by default, "use `{}`" to get hygiene, templates, etc.

I finally got around to reading that one. Interesting.

* There's the usual confusion/disagreement on what hygiene is. I could rant about this (again), but I won't.
* The general consensus in that thread seems to be that D mixins are not hygienic.
* If "hygienic" meant "better than C, which ignores scopes", then Walter Bright would have a point, I guess. But it means more than that, and so he kinda doesn't.
