### ISSUE TITLE
Installation of custom operators sits on the wrong peg

### ISSUE THREAD

**Issue by masak** [masak/007#173]
That peg currently being `sub` or `macro` statements. But this should work:

```
$ bin/007 -e='constant infix:<?> = sub (lhs, rhs) { return "?" }; say(1 + 2)'
3
$ bin/007 -e='constant infix:<?> = sub (lhs, rhs) { return "?" }; say(1 ? 2)'
Could not parse program
```

That is, the `constant` declaration of `infix:<?>` should introduce an operator into the current scope.
- (Putting a non-function into a constant that has the name of an operator should probably be an error.)
- (Oh, and there's a consistency argument for having anon `macro` terms that I hadn't seen before.)
- Finally, `my infix:<?>` should be an error, because we don't want to introduce an operator into the scope that has no chance of being filled with a value.

Oh, and parameters are another vector to introduce custom ops. This should totally work:

```
$ bin/007 -e='sub foo(x, y, infix:<+>) { return x + y }; say(foo(1, 2, sub(l, r) { return str(l) ~ str(r) }))'
Type check failed in binding to $c; expected Val::Sub but got Val::None (Val::None.new)
```

(Expected result: `12\n`, like with the corresponding below code.)

```
$ bin/007 -e='sub foo(x, y, c) { return c(x, y) }; say(foo(1, 2, sub(l, r) { return str(l) ~ str(r) }))'
12
```

Parameters to `if` and `for` and `while` blocks, too. Man, that would be sweet.

The two crazy ones are `class` declarations and `catch` blocks. Both of these should probably simply not be allowed to use operator names.

**Comment by vendethiel** [comment]
Makes the arity checking a lot harder...

**Comment by masak** [comment]
In the case of `constant`, we can still do arity checking at compile time. In the case of passing a value to an operator parameter, all bets are off. Though once we have a good enough #33, we can recover that.

    sub foo(infix:<+>) {}    # the name gives the parameter an implicit type (any, any) => any
    my bar = sub wrong-arity(x, y, z) {};  # gets implicitly typed as (any, any, any) => None
    foo(bar);    # the type checker would catch that

**Comment by masak** [comment]
This turned out to be the issue that kept be awake in bed last night. :smile:

The big realization from that sleeplessness is that this issue will end up clearly separating (in some cases) *introducing* an operator from *defining* it. This was always done at the exact same time in the case of `sub` and `macro` statements.

> (Oh, and there's a consistency argument for having anon `macro` terms that I hadn't seen before.)

I think the use case goes something like this:

    constant infix:<?> = some_computation()
        ?? macro(lhs_q, rhs_q) { ... }
        !! macro(lhs_q, rhs_q) { ... };

At least that thought is possible to think, and it's not obviously insane. Maybe one day someone will even find a meaningful use for it, and be delighted that it works. I see no good reason it shouldn't just work.

Given that `constant` statements require an assignment, they only separate introduction and definition a little bit. With parameters, it's more interesting, since they separate them by a caller/callee boundary.

But more importantly, it's the scope where the operator is *introduced* that's going to actually contain and parse the operator. Which means &mdash; crazily &mdash; that there's a case for traits on both constants and parameters. Also, the case for traits on sub terms is not so strong anymore, at least not if all our traits do is control precedence, associativity, and `is parsed`.

    sub foo(infix:<+> is parsed(/.../)) {
        # ...
    }

**Comment by masak** [comment]
> The two crazy ones are `class` declarations and `catch` blocks. Both of these should probably simply not be allowed to use operator names.

Ahahahah.

* If we go ahead with #308, then classes end up being a type of Callable, and thus could very well be infix operators. I'm still not convinced it leads to good _code_, ever, but it'd be terribly consistent if it just worked. Too consistent to pass up, even. (P.S. I'm still not sure we'll make classes work like that.)
* It's recently come to my attention that [`throw` statements don't have to limit themselves to exceptions, and there may be unexpected benefits to that](https://twitter.com/carlmasak/status/994213505552257026). Now, again, I'm not claiming that it's _a good idea_ to throw an infix operator and then catch it on the other side; I'm just saying it might be premature to forbid it.

**Comment by vendethiel** [comment]
> It's recently come to my attention that throw statements don't have to limit themselves to exceptions, and there may be unexpected benefits to that.

This is reminiscent of the difference in Ruby between `raise`/`rescue` and `catch`/`throw`.

**Comment by masak** [comment]
> Finally, `my infix:<?>` should be an error, because we don't want to introduce an operator into the scope that has no chance of being filled with a value.

I was wrong about this one. Operators are subs, and operator _applications_ like this one

    1 ? 2

Conceptually translate to a func call

    infix:<?>(1, 2)

A `my` initialization runs before the call, so the function is there when the call is made. So `my` statements work.

**Comment by masak** [comment]
I'm surprised I didn't see that when I saw that parameters could introduce operators.
