### ISSUE TITLE
Correct but slightly weird parse failure involving ->

### ISSUE THREAD

**Issue by masak** [masak/007#175]
This fails, which is maybe just as well:

    $ bin/007 -e='sub infix:«->»(lhs, rhs) { return "blah" }; say(1 -> 2)'
    Could not parse program

...but *why* does it fail? The operator exists, and it works if I don't call it `->`:

    $ bin/007 -e='sub infix:«!»(lhs, rhs) { return "blah" }; say(1 ! 2)'
    blah

Inquisitive minds want to know. :smile:

**Comment by vendethiel** [comment]
... because `->` is lambda. You want to catch it when defining the operator?

**Comment by masak** [comment]
For the purpose of long-term good error messages, yes, I think I'd like to catch it. Perl 6 has the concept of `<infixstopper>`, and `->` is one. Maybe we'll end up needing it in 007 too. Then requiring that a defined infix isn't an infix stopper would make a whole lot of sense.

For the purpose of this issue, I just want to figure out why it parsefails! :smile:

**Comment by vendethiel** [comment]
Because it parses an xblock, it seems:
```
https://github.com/masak/007/blob/2b235c3003656b01a3ef4db8611270648f6856d9/lib/_007/Parser/Syntax.pm#L153
```

EXPR is `1`, then it parses `lambda` (`'->'`) and fails.

**Comment by masak** [comment]
The `xblock` rule is only called from `statement:if`, `statement:for`, and `statement:while`... But `say(1 -> 2)` is a `statement:expr`.

**Comment by masak** [comment]
https://twitter.com/munin/status/767947883563843588

**Comment by vendethiel** [comment]
time to Debugger? (I know, you don't like it)

**Comment by masak** [comment]
No, you're probably right.
