### ISSUE TITLE
Wrong precedence when defining a postfix op with the same name as an existing prefix op

### ISSUE THREAD

**Issue by masak** [masak/007#190]
$ bin/007 -e='sub postfix:<!>(_) { return 5 }; say(^7!)'
    5

But this should print `[0, 1, 2, 3, 4]`, because the defined `postfix:<!>` should evaluate *before* the built-in prefix:<^>, because it should be tighter, because postfixes should by default always be tighter than prefixes.

From #189 we know that the order of the operators within the precedence space is actually correct &mdash; most likely it's the lookup that gets screwed up somehow, and 007 wrongly finds `prefix:<!>` when it should be looking for `postfix:<!>`. This is corroborated by the problem vanishing when a non-builtin operator name is used:

    $ bin/007 -e='sub postfix:<☠>(_) { return 5 }; say(^7☠)'
    [0, 1, 2, 3, 4]

**Comment by vendethiel** [comment]
This ticket's objective is to revert 4423c0a7b8a1646320e94f70f698272484066eb5.

**Comment by masak** [comment]
No, github, I didn't close this issue. Thanks for teaching me not to use the word "fix" before an issue number, though. :smile:

**Comment by masak** [comment]
> This ticket's objective is to revert 4423c0a7b8a1646320e94f70f698272484066eb5.

Yes, to be able to revert it, without test failures.

And now also 7bef7bc4f4e9afff1bb7617ee4b4341bac2e8349.

**Comment by masak** [comment]
Uhh.

Found the problem.

        sub tighter($op1, $op2, $_ = $*parser.opscope.prepostfixprec) {
            .first(*.contains(name($op1)), :k) > .first(*.contains(name($op2)), :k);
        }

So we're looking for the first operator with the `name($op1)`. What's `name`? I'm glad you ask:

        sub name($op) {
            $op.identifier.name.value.subst(/^ \w+ ":"/, "");
        }

Yes, it strips out the operator category, the `prefix:` or `postfix:` bit. Making `prefix:<!>` and `postfix:<!>` indistinguishable.

I wonder if the simplest fix isn't simply to *pass* the category when we call `tighter` et al. We do seem to have enough information at the call site. I am going to try that now. And then I will write a (builtins-independent) test to make sure I caught the bug.
