### ISSUE TITLE
The truthy multi doesn't cover all our values

### ISSUE THREAD

**Issue by masak** [masak/007#21]
We have

    multi truthy(Val::None) is export { False }
    multi truthy(Val::Int $i) { ?$i.value }
    multi truthy(Val::Str $s) { ?$s.value }
    multi truthy(Val::Array $a) { ?$a.elements }

But we also have `Val::Block`, `Val::Sub`, and `Val::Macro` (all of which are always truthy). We then use `truthy` from (currently) three places in the 007 code:

* `if` statements
* `while` loops
* the `grep` built-in

All of these would fail to dispatch if they got one of the three types of value we don't cover.

We should

- [x] make sure that this is actually the case
- [ ] write one or more tests for the expected behavior
- [ ] fix it

Possibly the fix is as simple as adding a `Val` candidate.

**Comment by masak** [comment]
Yes, this is actually the case:

    $ perl6 bin/007 -e='sub foo() {}; if foo { say("OH HAI") }'
    Cannot call truthy(Val::Sub); none of these signatures match:
        (Val::None)
        (Val::Int $i)
        (Val::Str $s)
        (Val::Array $a)

**Comment by vendethiel** [comment]
I'd argue it's always an error. You don't want "if sub"

**Comment by masak** [comment]
> I'd argue it's always an error. You don't want "if sub"

I see what you're saying, but saying "functions are opaque reference types, and thus always true" seems easier to implement, and not really harmful. Here's the same thing working in Python, a language that usually likes to put up limits to what you can do:

    $ python3
    >>> def fn():
    ...   pass
    ... 
    >>> if fn:
    ...   print("OH HAI")
    ... 
    OH HAI

Maybe an even stronger argument is that (currently) 007 is not strongly typed at all. If you get a parameter from a caller and what to check it for truthiness, the program shouldn't randomly fail just because the parameter happens to hold a function type.

**Comment by vendethiel** [comment]
Your language, your call, it's just that I dislike bool coercion in general :-).

**Comment by masak** [comment]
> Your language, your call, it's just that I dislike bool coercion in general :-).

Yeah, bool coercion definitely stays. When in doubt, 007 strikes a middle road between Perl 6 and Python &mdash; and both of those languages do implicit coercion in if/while/grep.
