### ISSUE TITLE
Dynamic variable not found, which leads to error with simple quasi

### ISSUE THREAD

**Issue by masak** [masak/007#226]
$ bin/007 -e='macro moo() { quasi {} }; moo()'
    Dynamic variable $*expr-last-statement-value not found
    [...]

Need to investigate this; surely the error come from the fix of #206, which introduced `$*expr-last-statement-value` in the code base.

**Comment by vendethiel** [comment]
Why is the code not using a simple return? I mean this part: https://github.com/masak/007/commit/626dfc13a5cbb2773b2e7ff803cd08c38f37b004#diff-9899783fe59fab654c1af1b0c082ed2dR710

**Comment by masak** [comment]
@vendethiel I don't quite understand the question. Maybe you could outline how the code looks if it used a simple return?

**Comment by vendethiel** [comment]
I'm probably missing a corner case, but here we go:

```perl6
    method run($runtime) {
        my $last-statement;
        my $statement-count = +$.statements.elements; 
        for $.statements.elements -> $statement {
            my $value = $statement.run($runtime);
            my $is-last-statement = ++$ == $statement-count;
            if $is-last-statement && $statement ~~ Q::Statement::Expr {
                $last-statement = $value;
            }
        }
        return $last-statement;
    }
...
    method eval($runtime) {
        return $.statementlist.run($runtime);
    }
```

**Comment by masak** [comment]
That... might actually work. :smile:

PRs welcome. Or I might try writing it that way myself. Basically, if the tests pass with that change, it'll be good enough.

**Comment by vendethiel** [comment]
I can confirm the tests still pass. Will PR.
