### ISSUE TITLE
Kill off PropertyList, TraitList, ParameterList, ArgumentList

### ISSUE THREAD

**Issue by masak** [masak/007#249]
Or at least try. I don't currently remember why we bother to have them at all.

All they do is sit there containing an array of (respectively) `Property`, `Trait`, `Parameter` and `Expr`. (Yeah, that last one is funny. I know.) Why not just *remove the middleman* and store that array directly?

If that's a thing we can do, then we better do it before 1.0.

(There's also some thinking we should do to provide various macro API conveniences around these arrays of things. But I don't imagine removing these `-List` Qtypes will make that more difficult; rather the reverse.)

**Comment by vendethiel** [comment]
Wasn't that done this way to help splice list into quasis?

**Comment by masak** [comment]
Yes, maybe. Maybe their sole *raison d'être* is as a convenient "level" at which to quasi-inject things.

Closing this issue for now, until evidence to the contrary surfaces.
