### ISSUE TITLE
Remove method shorthand from Dict

### ISSUE THREAD

**Issue by masak** [masak/007#261]
After #242 is merged, we might want to remove the method shorthand on the Dict type. I don't see a big need for declaring "methods" on dictionaries, now that `Object` and `Dict` have separated. People are much more likely to declare methods using the `class` syntax from now on.

**Comment by sergot** [comment]
Why is it currently blocked? :)

**Comment by vendethiel** [comment]
Because #242 wasn't merged I guess

**Comment by masak** [comment]
What @vendethiel said. Currently the `master` branch doesn't have a `Dict` type. This issue was one of the things belonging to the separation of the `Object` and `Dict` types, but it's not a hard requirement for #242, which is already rather huge.

**Comment by sergot** [comment]
Oh I didn't notice, thanks!
