### ISSUE TITLE
Rename the language

### ISSUE THREAD

**Issue by masak** [masak/007#277]
Please take the following with a appropriate grain of salt.

I'm thinking if this language ever ended up [in a book](https://github.com/masak/compiler-book), then its current name would be at best a bit unfortunate, and at worst a [legal problem](https://en.wikipedia.org/wiki/Trademark_infringement).

I haven't decided to rename it yet. If I did, I don't really know what we'd call it. Open to suggestions and, at this point, bikeshedding. :bike: :paintbrush: 

Connotations that we'd like to evoke: smallness, orthogonality, ease of use/understanding, can consume itself.

Currently I'm leaning towards the name *Simplex*. In geometry, it's a simplest possible polytope such as a triangle or tetrahedron. It's the opposite of "complex". The [synonyms](http://www.thesaurus.com/browse/simplex) are nice, too. A quick search doesn't reveal another programming language with this name. (However, there exists [an algorithm](https://en.wikipedia.org/wiki/Simplex_algorithm) with that name.)

**Comment by masak** [comment]
Closing this issue as this is not currently a concern.

**Comment by masak** [comment]
I'm warming up to *Alma*, short for "**Al**goloid with **Ma**cros".

The name seems to be available, though (I just found out) there's an [Alma-0](https://en.wikipedia.org/wiki/Alma-0) already.

**Comment by masak** [comment]
I also toyed with naming it either *Grace* or *Hopper* (in honor of [the inventor of the compiler](https://en.wikipedia.org/wiki/Grace_Hopper)) or even *Hop* (in honor also of beer). But of course those three are taken already, even if it seems to be for fairly small initiatives.

**Comment by FCO** [comment]
In portuguese `alma` means `soul`

**Comment by masak** [comment]
Oh, so it does. Seems to be from Latin [anima](https://en.wiktionary.org/wiki/anima#Latin).

**Comment by masak** [comment]
I made a rough sketch of Alma's logotype. It gets its inspiration from [a certain butterfly](https://www.perl6.org/camelia-logo.png), while still trying to be its own thing.

![image](https://user-images.githubusercontent.com/20627/54753812-455e2280-4be2-11e9-9f81-d93c8dd31512.png)

Another thing it might be too close to is [this book cover](https://www.amazon.com/Modern-Perl-chromatic/dp/1680500880/), which would be unfortunate, I guess. The solution might be to make Alma's logotype even more abstract.

Might also adopt this logotype for 007 pre-rename, even though the connection isn't really there between name and logotype.

**Comment by masak** [comment]
Also symbolic, I realized, that while Camelia has a big yellow smiling face with big eyes in the middle, Alma's logotype has just [negative space](https://en.wikipedia.org/wiki/Negative_space), just like we aim to have ["no core", but instead just a meta-circular definition of the language](https://github.com/masak/007/issues/305).

**Comment by masak** [comment]
Reopening. It's happening.

I'd like for this to happen fast. As long as we accept a PR that does all the renaming &mdash; nice and slow &mdash; we also rename the repo and close this issue.
