### ISSUE TITLE
Should 'extends' be an annotation

### ISSUE THREAD

**Issue by masak** [masak/007#285]
Should we instead of...

    class B is A {}
    class B extends A {}

(I've been inconsistent about the exact keyword elsewhere in the issues)

...use...

    @extends(A)
    class B {}

...?

I'm a bit torn. I'm pretty sure we'll end up using annotations now, à la #257. They offer the opportunity to clean up a lot of "special cases" in the form of random keywords like the `is` or `extends` above.

But on the other hand, I find the lower form, the one with the annotation, to be kind of ugly. I'm unable to separate myself from my own bias here; am I just unused to it, or is it objectively worse?

I'm less torn about giving public/private modifier this treatment, or final fields, or lazily initialized fields, or non-overridable methods... maybe I'll even go so far as to remove `constant` from the language and replace it with `@constant my`... but the above one still strikes me as not necessarily an improvement.

What do you think, dear reader?

**Comment by vendethiel** [comment]
Why? If `class` is a built-in language feature, then i'm fairly sure`extends` should be as well. If we're constructing a MOP from the ground up (like Common Lisp's), where classes are built on other things which are user-available (though dangerous), then it makes sense.

**Comment by masak** [comment]
Well, I think we might be constructing a MOP from the ground up... but you've answered my question anyway. Thank you.

Let's go with the traditional syntax for now. Closing.

**Comment by masak** [comment]
Oh! Here's an excellent reason to keep `extends` as a keyword _after_ the class declaration:

    class Derived<T> extends Base<T> {
        # ...
    }

That is, it's entirely reasonable (and common) to introduce a type parameter in the class name, and then to use it as a type argument in the `extends` clause. If we used a trait instead, the order would be backwards, and `T` wouldn't be bound yet in the trait.
