### ISSUE TITLE
Retire double-colon (::) as module separator: Turn Q::Statement::If into Q.Statement.If

### ISSUE THREAD

**Issue by masak** [masak/007#298]
A fallout of #248, although I had been thinking about it on and off even before that, so it's probably the right idea.

Could profitably be done along with #250.

Note that this more clearly frees up `::` as a possible infix operator, although I suggest we leave it unclaimed for now. (<del>I still like `array.concat` better for array concatenation.</del> (*Update*: we actually had `infix:<::>` as our "cons" operator until I removed it recently in https://github.com/masak/007/commit/0de12805f57d42c577ceb3bf0b2422ff0f41a86a. It had its own precedence level and everything. The fact that I confused it here with array concatenation (which we never found a good operator name for) should tell you a little bit about how rarely I used it.)) People can play with it as a user-defined operator for a while.

**Comment by masak** [comment]
No, I think it's worse than that. We're about to make #250 _moot_ by turning everything into a property access. `x.y.z` is just two property accesses, not a `name` in the #250 sense.

Not saying it can't be done, but it will require more deliberate actions than just search-and-replace.

**Comment by vendethiel** [comment]
> A fallout of #248

I'm not sure how?
I think this ticket is missing a "motivation" part.

**Comment by masak** [comment]
> I think this ticket is missing a "motivation" part.

Good point. Let me fix that.

Python and JavaScript get along just fine with `.` for "package/module member", along with its usual meaning of "object property". That's because, in Python and JavaScript, package/module members _are_ a kind of object properties. For 007, I'd rather have one unified syntax than two different ones.

But I'm also having some second thoughts, mostly because something like `Q.Statement` would need to be both a class and a module to hold things like `Q.Statement.My`... and we don't have a coherent story for that, so maybe we should hold off for now.

**Comment by masak** [comment]
> mostly because something like `Q.Statement` would need to be both a class and a module to hold things like `Q.Statement.My`

No, I think I came at that wrong. Not only do I find it hard to picture something being both a class and a module, but I don't think we need it in this case.

I think we could make it work by defining the whole `Q` hierarchy inside the `Q` class as nested static classes. `Q` would contain `Q.Statement` would contain `Q.Statement.If`, etc. (And they'd also extend each other in the opposite direction.) It all works out, by being a one-shot definition of everything. I can see that fitting neatly into a `builtins.007`, actually.

The big loss we'd suffer under this scheme is that a macro author wouldn't be able to lay claim to (say) `Q.Statement.Switch` for their own enjoyment, because at that point, the "name hierarchy" (if not the class hierarchy) would be closed for extension. You can't add a `Q.Statement.Switch` after the fact, because the static properties of `Q.Statement` have already been set once and for all, because the (immutable) `Type` object for `Q.Statement` has already been created.

At least I _think_ so... I mean, clearly a `Type` object needs to be mutable to the extent that they are created as soon as we declare a class (so that we can refer to it in order to extend it etc), but then as we keep parsing the class body we'll send the `Type` object instructions for what properties/methods it'll have... so maybe it *is* possible to add a static property later?

Or maybe it can be _made_ possible by messing around with an appropriate meta-`Type`, #266-style...? As usual, my head hurts thinking about that.

**Comment by masak** [comment]
Just swinging by this issue to say that the more I think about this, the more _emotionally_ convinced I am that we should do this. There's simply no separate benefit to `::` as distinct from `.`.
