### ISSUE TITLE
'else' ought to accept a parameter

### ISSUE THREAD

**Issue by masak** [masak/007#323]
This works:

    if 42 -> v {
        say("The value is truthy and it's " ~ v);
    }

But this doesn't:

    if 0 {
    }
    else -> v {
        say("The value is falsy and it's " ~ v);
    }

It should, in my opinion. Not because it's a terribly useful feature, but (a) it works in Perl 6, and (b) at some point someone is going to try it just for the heck of it, and then we'd have to explain why all other blocks take a parameter but not the `else` block.

We should probably have a test or two for this too.

**Comment by masak** [comment]
Huh! This made me think. I wonder if it would make sense to let exceptions boolify to `False`. That way, we could have code like

    if someOperation() -> value {
        # do something with value
    }
    else -> exception {
        # do something with exception
    }

Note that `someOperation()` would then have to _return_ the exception, not throw it.

I dunno. The phrase "interesting values of `False`" gets thrown around sometimes in the Perl 6 world, and it seems that this would accommodate that. But I'm not 100% certain making exceptions falsy might not lead to a WAT on the order of [making midnight falsy](https://lists.gt.net/python/python/723174) &mdash; that's the thing, cute features can come back to bite you as WATs in ways that basically can't be predicted.

**Comment by vendethiel** [comment]
I'm not sure if should handle exceptions. Seems like this is reinventing Failure and `with`/`orelse` in the same ticket.

**Comment by masak** [comment]
Yep, I hear you. I'm not convinced either.

Either way, this issue is super-simple and _only_ about making `else` an `xblock` in the grammar. My musing about exceptions was mostly about trying to think of a use case for that, no matter how contrived.
