### ISSUE TITLE
Enum values -- upper-case or lower-case?

### ISSUE THREAD

**Issue by masak** [masak/007#390]
Just thinking out loud here.

Different languages seem to have differing conventions. In Java, the convention seems to be to use [ALL_UPPERCASE](https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html) for the enum values. [So does Python](https://docs.python.org/3.8/library/enum.html). Perl 6 seems to be using sometimes all-lowercase, sometimes CamelCase. TypeScript also uses [CamelCase](https://www.typescriptlang.org/docs/handbook/enums.html).

I'm thinking the ALL_UPPERCASE form is probably both the most popular form, and the most reasonable &mdash; enum values are, after all, a form of constants.

I see no "logical" support at all for the CamelCase form &mdash; although, admittedly, it's easier on the eye.

I'm thinking we might go with the ALL_UPPERCASE form in all our examples and documentation, and then leave it up to people how to do it in their code.

Closing. 😄

**Comment by masak** [comment]
We're discussing this on #perl6-macros now. I'm slowly coming to the opposite conclusion &mdash; enum values should be lower camelcase, _because_ in the end they are just instances of the entire enum.

The fact that they're constants is, in the end, probably not important enough to mark them with ALL_UPPERCASE the whole time. It seems odd, for example, to make them as scream-y as phasers.

This would also mean we should rename `True False None` to `true false none`. That'd put us in line with JavaScript, Java, and C#.

**Comment by NicoHood** [comment]
The official python docs use upper case. It is the recommended way for enums

**Comment by masak** [comment]
> The official python docs use upper case. It is the recommended way for enums

Haha, yes, thank you @NicoHood. These two questions are pretty clear already, and there's no doubt around them:

* **Q: What does Python (stylistically) recommend for _user-defined_ enum values?** A: All-uppercase, possibly with underscores. As seen in [the official docs](https://docs.python.org/3/library/enum.html) and in [the cpython test suite](https://github.com/python/cpython/blob/cb1001ce23205eeed69395cdbfdb99e99a37aca1/Lib/test/test_enum.py).
* **Q: What does Python use for its _built-in/hardcoded_ enums `bool` and `NoneType`?** A: First off, these two types are not acknowledged to be enum types, although they seem to qualify. Second off, they are written as upper CamelCase, as seen here: [False, None, True](https://docs.python.org/3/reference/lexical_analysis.html#keywords).

So, Python uses a different convention for its built-in enum types than for user-defined enum types. This is OK for Python, since "the language decides" whether `bool` and `NoneType` are even to be considered enums. Since Python doesn't claim that they are, it gets away with doing that.

For Alma, that's not good enough. Alma blatantly declares both `Bool` and `None` types to be enum types; because of this, the built-in and user-defined versions should have the same convention. The final rationale for that convention is written above, and something that I still believe:

> enum values should be lower camelcase, _because_ in the end they are just instances of the entire enum.

Writing global constants with all-uppercase (with underscores) still makes sense to me. But when you package them into an enum, they can be lower camelcase.

From Alma's perspective, the Python convention of ALL_UPPERCASE_UNDERSCORES is a holdover from when enum values were loosely grouped globals, and the other Python convention of naming `True`, `False`, and `None` as if they were type names doesn't make sense at all.
