### ISSUE TITLE
Make parsing of calls to postdeclared subs work

### ISSUE THREAD

**Issue by masak** [masak/007#4]
Just discovered this:

    $ perl6 bin/007 -e='sub foo() { say("OH HAI") }; foo()'
    OH HAI
    $ perl6 bin/007 -e='foo(); sub foo() { say("OH HAI") }'
    Variable 'foo' is not declared
      [...]

[We even have a test](https://github.com/masak/007/blob/d6434466062a47114897bb03c39147f158036ded/t/semantics/subroutines.t#L67-76) for this to work, and it does, on the AST level. The problem is that the parser does not allow the program through.

The immediate fix is to defer checking whether a variable is declared until we discover that we're *not* making a call to it. So the statement `foo;` is wrong if `foo` is not a declared variable, but the statement `foo();` gets a free pass. (I'm not sure where that means the declared-variable check should happen. It should still happen ASAP. Probably somewhere inside the expression parser.)

Of course, this should still be an invalid program:

    $ perl6 bin/007 -e='{ bar() }; BEGIN { say("never get here") }'

Because we still *do* make declared-variable checks, but we defer them to the end of the block.

I'm undecided about what we should do with this type of situation:

    $ perl6 bin/007 -e='bar(); my bar = -> { say("OH HAI") };'
    $ perl6 bin/007 -e='bar(); my bar = 4;'

Strongly leaning to emitting a custom error for that, something like "you called this thing as if it was postdeclared, but then you didn't use `sub` to postdeclare it". I went through Rakudo core's exception types, and I didn't find a good one for that already existing.

**Comment by Mouq** [comment]
Alternatively, you could make any unrecognized idents go on a waiting list to see if it gets declared later in an outer scope. If it comes across an a function definition, fine. If it's declared as a variable, error with "Variable <ident> used before declaration at line ....". If it's left unresolved, die with "Unrecognized identifier <ident> at line ...", possibly with "did you mean...?".

**Comment by masak** [comment]
Certainly. There's a slight difference in what would be allowed.

    $ perl6 bin/007 -e="sub bar() {}; say(bar)"  # already works
    <sub>
    
    $ perl6 bin/007 -e="say(bar); sub bar() {}"  # would work under Mouq's proposed semantics but not masak's
    Variable 'bar' is not declared
    
    $ perl6 bin/007 -e="say(bar()); sub bar() {}"  # would work under both Mouq's and masak's semantics
    Variable 'bar' is not declared

But I don't see the harm in allowing not just *calls* to post-declared functions, but any kind of mention of them. If anything, that feels more consistent.

So yes, I think I prefer Mouq's semantics. It's probably easier to implement, too, since it doesn't have to have the above-mentioned check inside `EXPR`.
