### ISSUE TITLE
Subs and macros are never equal to themselves

### ISSUE THREAD

**Issue by masak** [masak/007#40]
These three all return `0`, but I believe they should return `1`.

    $ perl6 bin/007 -e='sub foo() {}; say(foo == foo)'
    0
    $ perl6 bin/007 -e='macro foo() {}; say(foo == foo)'
    0
    $ perl6 bin/007 -e='say(infix:<+> == infix:<+>)'
    0

Also, this one shouldn't fail. Nor should any of the other `Q` types. Generally, they should be compared "by value".

    $ perl6 bin/007 -e='say(Q::Identifier("foo") == Q::Identifier("foo"))'
    Cannot call equal-value(Q::Identifier, Q::Identifier); none of these signatures match:
        (Val, Val)
        (Val::None, Val::None)
        (Val::Int $r, Val::Int $l)
        (Val::Str $r, Val::Str $l)
        (Val::Array $r, Val::Array $l)

Arguably, this one should still be `0`, though:

    $ perl6 bin/007 -e='my a = []; for [1, 2] { sub fn() {}; a = [fn, a] }; say(a[1][0] == a[0])'
    0

(That is, even those two `Val::Sub`s were created from the same `Q::Statement::Sub`, they were created in different frames, and so they're different.)

**Comment by masak** [comment]
I'm having second thoughts about that last one. Turning this over in my head literally kept me up last night.

Long story short, I think we want to compare on the *contents* of `Val::Sub`, just like we do with the other types. That is, two subs are equal if they have equal name, parameters, and statements. This gives the semantics I intend in all the ways I can think of.

We don't compare outer frame, though. It would make objects not equal if they were created from the same. In particular, with the chosen semantics, objects can compare structurally, and will mostly behave as expected from structural comparison.

I was toying the idea of including the *position* in the source code in the sub comparison. That would eliminate false positives between two identical subs in different places in the code. But I'm not sure it's worth the extra complexity.

**Comment by vendethiel** [comment]
> Long story short, I think we want to compare on the contents of Val::Sub, just like we do with the other types. That is, two subs are equal if they have equal name, parameters, and statements. This gives the semantics I intend in all the ways I can think of.


That's a bit scary, though... Brings ES' Function::toString in mind...

**Comment by masak** [comment]
> That's a bit scary, though... Brings ES' Function::toString in mind...

Hehe, don't worry. I just want to solve the problem of comparison for equality. `Val::Sub` values are still opaque and can't be introspected. Not sure what I'd like the stringification to show. Probably just the name and the signature?

**Comment by vendethiel** [comment]
probably yes

**Comment by masak** [comment]
> Not sure what I'd like the stringification to show. Probably just the name and the signature?

And then my brain went "oh noes, we're re-creating the `Function#toString` nightmare all over again!" :)

But I think it's not that bad. People did introspection via `Function#toString` in JavaScript because that was the *only* option that worked cross-platform. In 007, I expect we'll en up with both a MOP and the Qtrees, both of which ought to be able to handle introspection better than parsing strings.

Some people still might parse the stringification of the sub. Sigh. :) Maybe let them. And then think about how to make beginners stumble more easily over the other, better solutions.

We're still not showing the statements in the stringification. That's non-negotiable. From the point of view of the runtime, a `Val::Sub` is a black box. It does not have any visible moving parts that you can inspect and analyze. You can call it, and that's it.

**Comment by vendethiel** [comment]
Maybe "{ ... }" would work.

**Comment by masak** [comment]
Yeah, maybe. I'm not too worried about the stringification. Either of these would be fine by me:

1.` <sub>`
2. `<foo>`
3. `<foo(x, y)>`
4. `<sub foo(x, y)>`
5. `<sub foo(x, y) { ... }>`

So far no. 4 is my favorite. All of the parts add some information. (The `sub` distinguishes it from a macro.) And the surrounding `< >` symbols make it a little distinct from a string.

**Comment by masak** [comment]
> Long story short, I think we want to compare on the *contents* of `Val::Sub`, just like we do with the other types. That is, two subs are equal if they have equal name, parameters, and statements. This gives the semantics I intend in all the ways I can think of.

When I arrived at this, I was a little worried that somewhere this semantics might introduce an infinite loop in some cases. But I think that worry is unfounded. `Val` types don't occur in `Q` hierarchies.

**Comment by masak** [comment]
> But I think that worry is unfounded. `Val` types don't occur in `Q` hierarchies.

They *do*, nowadays that we're more self-hosting. But still there's no risk, because there's no case of a `Val::Sub` in any of the Q node types.

**Comment by vendethiel** [comment]
I need to try it on my computer, but huh... Do we compare the outer frame of subs to declare them equal nowadays?
