### ISSUE TITLE
masak/bresenham

### ISSUE THREAD

**Issue by claes-magnus** [masak/007#450]
### Suggestion 

 In examples/bresenham-line.007 at the masak/bresenham branch, replace the . and # with...

 my EMPTY = "░";
 my FILLED = "●";

*That would accomplish this lovely output:*

![bresenham](https://user-images.githubusercontent.com/42797326/50508278-7b778480-0a81-11e9-8d2d-ddfda7f7d57e.png)

**Comment by masak** [comment]
Thanks for the suggestion!

I think I'll keep it as ASCII, for mostly paranoid reasons. ASCII has super-wide support; as soon as we start experimenting with characters outside of that, we're at the mercy of all kinds of strange character decoding issues.

All is not lost, though. Thanks to the power of Unix pipelines, anyone who wants different characters without modifying the script can easily post-process the output using (e.g.) `sed`:

```sh
$ bin/007 examples/bresenham-line.007 1 1 20 23 | sed -e 's/\./░/g; s/#/●/g'
```

Again, thanks for the input! Closing.

**Comment by claes-magnus** [comment]
Ok!
But ░ is ASCII? The dot is unicode though... Perhaps (one last try) ░ and . ?

**Comment by claes-magnus** [comment]
https://fsymbols.com/images/ascii.png

Yes? 176

Aren't all 256 chars included? Back in the days this char and others were at least included in ASCII art?

**Comment by vendethiel** [comment]
That’s « extended ASCII »

**Comment by masak** [comment]
You jest, but here we don't try to count authority, but instead evaluate hypotheses against [reality](https://en.wikipedia.org/wiki/Extended_ASCII).

**Comment by masak** [comment]
I think my point was, that if you need it I can give you my personal assurance that Ven isn't the Devil... but the need for such an assurance shouldn't have to enter into the equation, since he's factually right.

["Je n'ai pas eu besoin de cette hypothèse"](https://en.wikiquote.org/wiki/Pierre-Simon_Laplace).

**Comment by claes-magnus** [comment]
Yes, sorry for what I believed would be an obvious (but bad) joke, separated into a post of its own and from my real reply ’ah, ok :)’

**Comment by vendethiel** [comment]
I had no doubt it was a joke, fwiw, and I think neither had masak.

**Comment by claes-magnus** [comment]
...then I don't understand masaks replies at all. but nevermind. :) anyways, sorry for writing and taking time from more interesting stuff.
