### ISSUE TITLE
Get rid of Tuple

### ISSUE THREAD

**Issue by masak** [masak/007#459]
I was happy when we got `Tuple` in the language. Quoting #274:

> Python has one, and for good reasons. It's a sequential type whose values can't be modified after creation.

Because they are immutable, they are also _hashable_.

> Another nice thing about tuples is that we can hash on them

A third advantage might be the different expectation/semantics on the tuple type: while the `Array` type is expected to be typed in a homogeneous way, the `Tuple` is expected to be typed heterogeneously. More generally, the elements of a tuple are expected to vary by _position_, whereas those of an array, generally, are not.

In this issue I make the impassioned case that these three virtues are not positive enough to outweigh the negative of a whole new core type in the language.

Let's go over the advantages again, now with counterarguments.

**Sequential immutable type.** Immutability is nice, and is probably the strongest argument for having the type in core. But, two counterarguments:

* (a) I've yet to encounter a place where handing back an `Array` instead of a `Tuple` was an absolute deal-breaker. Defensive copying usually works when it is, and even in cases where it isn't (for performance reasons or whatever), we can just fall back to "well, don't mutate it, then".
* (b) What about immutable `Dict`s? Couldn't we do this as a `freeze` builtin instead, that wraps our container in an equivalent but immutable one?

**Immutable, therefore hashable.** Well, yes. But again, what about hashable `Dict`s? It feels disproportional to introduce a separate `Map` type just to have an immutable/hashable counterpart to `Dict`. It strikes me that the `freeze` built-in could make things not just immutable, but hashable too. That seems a pleasing solution to me. If that's not an option for some reason, then we could always go with Ven's idea in https://github.com/masak/007/issues/184#issuecomment-245524386.

**Arrays are homogeneous, tuples are heterogeneous.** I think I would consider this argument a strong one, if TypeScript hadn't already led the way and shown how to use `Array` _both_ as an array type and a tuple type. That is, `[string, number, boolean]` is a TS 3-tuple, but it's also a subtype of `Array`.

Furthermore,

* They are yet another language primitive to learn. Objectively, the language is smaller and simpler without them.
* It seems to me that the "JSON model" has something very nice and minimal in it. It has arrays (`[]`) and objects/associative arrays (`{}`), but no tuples (`()`). Why not? Because from JSON's perspective, tuples would carry absolutely no advantage over arrays.

I read through all our issues (open and closed) mentioning "tuple". The `divmod` operator from #330 will need to return an array instead. Some code in the musing in #345 will need to switch to returning arrays. That's all. Case in point.

In parting, I think `Tuple` would make a great addition to our growing set of ideas for modules. The syntax is already beta-tested.

**Comment by vendethiel** [comment]
It'd definitely be a deal-breaker, and an assessment to 007's maturity, if we managed to implement a syntax for Tuple (i.e. `#(1,2,3)`) via a macro.

**Comment by masak** [comment]
Agreed. (Though that doesn't seem like the conventional use of the word "deal-breaker".)

I was thinking we could even manage to give it back its _current_ syntax, `(1, 2, 3)`, by some neat combination of defining `term:<( )>` (or `circumfix:<( )>` if #434 comes to be), `is replacing` à la #421, and possibly `defer` à la #16.

**Comment by vendethiel** [comment]
Well, OK, I'll rephrase: having support for macros powerful enough to implement such a syntax would be a deal-breaker.

**Comment by masak** [comment]
I just wanted to pop in here and say that I liked what Dylan does with [`values`](https://opendylan.org/documentation/intro-dylan/expressions-variables.html#parallel-values). It's a purely syntactic thing (tuples aren't reified), and so `values` always gets compiled down to e.g. multiple assignments. In Dylan, it allows multiple returns.

The ethos of this issue is that tuples don't offer anything much over arrays, and I still believe that. But if I didn't, I would probably go with `values`.
