### ISSUE TITLE
Make unquote lexical lookup possible

### ISSUE THREAD

**Issue by masak** [masak/007#47]
Currently have this failing test locally:

    {
        my $program = q:to/./;
            macro foo() {
                my x = 7;
                return quasi {
                    say(x);
                }
            }

            foo();
            .

        outputs $program, "5\n", "a variable is looked up in the quasi's environment";
    }

It fails with:

    Variable 'x' is not declared
      in method find at /home/masak/ours/007/lib/_007/Runtime.pm:78

Essentially because it's looking in the wrong lexical scope: the mainline's, not the macro's. We've decided that we want lexical scoping/hygiene for this by default (in Perl 6, and therefore in 007), and so it *should* look in the macro's scope.

Let's just pause and recognize the fact that it should do that is absurd on the face of it. At the point of the lookup, the `say(x)` has been physically copied into the mainline, replacing the `foo()` macro call. Therefore, the current (wrong) behavior is certainly the *natural* one: the runtime would normally expect to look for `x` in the surrounding scopes, innermost first.

Some clever person may say "oh, no worries &mdash; let's just do what closures already do in that case to displace the lexical lookup!". But &mdash; newsflash &mdash; closures are great because they *preserve* the lexical lookup, while also allowing being passed around as first-class values between other, unrelated scopes. In other words, we get no help from closures, because all they do all day is be extremely consistent lookup-wise.

At a minimum, what the above example would need is two things:

* A way for a `Q::Block` to mark what its `OUTER` is. (At least if it's different from expected.)
* A way for a new `Val::Block` to be created so that it inherits this information.

Getting all these bits right (static blocks, dynamic blocks, outers, callers) is tricky. I need to mull it over some more before diving in.

**Comment by masak** [comment]
Now that we finally have #20 closed and static lexpads in the right place, I think it's time to really get to the bottom of this one.

**Comment by vendethiel** [comment]
When I first met 6's macros, I remember arguing it was more-than-surprising a behavior. Lisps will ask you to interpolate such values, resolving any issue scoping related.

**Comment by vendethiel** [comment]
It has the obvious drawback that, to prevent multiple evaluations, you'll need to start your quote with a let (in which you'll bury your unquote, in common lisp with a gensym)

**Comment by masak** [comment]
> When I first met 6's macros, I remember arguing it was more-than-surprising a behavior. Lisps will ask you to interpolate such values, resolving any issue scoping related.

> It has the obvious drawback that, to prevent multiple evaluations, you'll need to start your quote with a let (in which you'll bury your unquote, in common lisp with a gensym)

That went a bit too fast for me. (I got stuck on the exact referents of "interpolate such values", "multiple evaluations", and "bury your unquote".)

Could you maybe start from the original example in this issue, and explain what Lisp would do with it?

**Comment by vendethiel** [comment]
```lisp
defmacro foo (tree)
   (let ((namesyn (gensym)))
     `(let ((,namesyn ,tree))
        ; now I'm sure I can use ",namesyn", and it'll be evaluated only once
        ; using ",tree" all over the place would multi-eval
        ))
```

**Comment by masak** [comment]
Oh, well in that case I'm not sure Perl 6 and 007 are all that different.

    macro foo($tree) { quasi { ... {{{$tree}}} ... {{{$tree}}} ... {{{$tree}}} ... } }

That would multi-eval `$tree` too. By design.

What you'd have to do to single-eval it:

    macro foo($tree) { quasi { my $expr := {{{$tree}}}; ... $expr ... $expr ... $expr } }

**Comment by masak** [comment]
7702fdf has the details, but I'd better give my interpretation while I'm still lucid enough to understand it.

In brief, `Q::Term::Quasi ⇝[interpolate]⇝ Q::Block ⇝[eval]⇝ Val::Block`, with the `[interpolate]` step also capturing the surrounding context (usually a macro) for `[eval]` to slap on the `Val::Block`.

Coming back to what I theorized in the OP:

> At a minimum, what the above example would need is two things:
>
> * A way for a `Q::Block` to mark what its `OUTER` is. (At least if it's different from expected.)

That's correct &mdash; a `Q::Block.new` now takes an optional `$outer-frame` argument. Only `Q::Block.interpolate` uses this as part of quasi interpolation.

> * A way for a new `Val::Block` to be created so that it inherits this information.

Yes, `Q::Block.eval` now first checks the optional `$.outer-frame` attribute to see if it's set, or otherwise falls back to the normal `$runtime.current-frame`.

Thinking of extracting this special `OUTER`-setting semantics into a `Q::FrankenBlock` subrole. (Maybe with a slightly less spurious name.)
