### ISSUE TITLE
Provide some much-needed common operators

### ISSUE THREAD

**Issue by masak** [masak/007#57]
As part of #54, I think we'll realize there's a whole bunch of common operators missing.

- [x] arithmetic: `infix:<->` and `infix:<*>` (we'll skip `infix:</>` and `infix:<%>`)
- [x] string repetition: `infix:<x>`
- [x] array concat: <del>`infix:<concat>`</del> (I don't have an obvious symbolic name for this one. going for clarity until I find something nice. maybe even `concat(a, b)` would be preferable.)
- [x] head/tail cons: `infix:<::>`
- [x] array repetition: `infix:<xx>`
- [x] non-equality: `infix:<!=>`
- [x] comparisons: `infix:«<»`, `infix:«<=»`, `infix:«>»`, `infix:«>=»` (thinking of conservatively banning these for anything but ints and strs)
- [ ] type matching: `infix:<~~>` (where `x ~~ T` would mean something like <del>`type(x) == str(T)`</del> `type(x) == T`)
- [x] boolean operators: `infix:<||>`, `infix:<&&>`, `prefix:<!>`

All these are kind of low-hanging fruit, though I'm sure there are interesting corner cases where we'd need excellent tests to make sure we don't introduce undefined behavior.

**Comment by sergot** [comment]
can't concat become "~"?

**Comment by masak** [comment]
> I'm wondering if *concat* can become `~`, what do you think?

`infix:<~>` right now means string concatenation, just like in Perl 6. If 007 were to change its string concatenation operator to something else, it would be Python's (overloaded) `infix:<+>`, which works for numbers, strings, and arrays. So in that case, `concat` would simply be `infix:<+>`.

    $ python3
    Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
    [GCC 4.8.4] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> 1 + 2
    3
    >>> "1" + "2"
    '12'
    >>> [1] + [2]
    [1, 2]
    >>> 

But I'm unlikely to take that path, because I'm attached to Perl's idea that operators be grouped into "types" (numeric, string-y, list-y).

007 has inherited that idea right now &mdash; numeric `infix:<+>` is different from string-y `infix:<~>`. This is important in 007 for another reason: unlike Perl 6, 007 doesn't have a multi dispatch mechanism, and so it's more difficult to add new multis for the same operator. This points to the principle of 1-operator-1-type.

So `infix:<~>` can't both be for strings and for arrays. Besides breaking 007's unstated principle, it might also be taken as a (false) assertion that in 007, a string can be seen as an array of codepoints.

Lastly, I think I'm too used to `infix:<~>` meaning string concatenation to want to change. ☺

All in all, I don't see the case for `infix:<~>` meaning array concat being very strong. So far I haven't seen *any* operator that immediately yells "array concatenation". (Which is why different languages all tend to come up with their own variant for this operator, I guess.) So I'm proposing we go with `concat(array1, array2)` as a safe fallback.

**Comment by vendethiel** [comment]
`::`, `@`, `++`, `^` are options.

**Comment by masak** [comment]
> `::`, `@`, `++`, `^` are options. (that last one is ml string concat)

Assuming you mean they are options for an array concatenation operator (as opposed to, say, a string concatenation operator so that we can use `infix:<~>` for arrays). Let me quickly review them.

* `::` makes sense insofar as array/list operators in Perl 6 are sometimes doubled. (Cf. `infix:<xx>`). Currently though (see OP) this one is slated to mean `unshift`.
    * Note also that using this operator for anything is slightly risky, since `::` is valid in identifiers. The programmer will need to disambiguate with whitespace before the operator.

* `@` is out, because of its special meaning in quasis. The colon can bear to have many meanings in different contexts, but not this one. At least not if the meanings aren't strangely consistent.

* `++` was my favorite for a while as I thought about it. But (because 007 is more lenient with whitespace before postfix than is Perl 6) this would prevent `postfix:<++>`, which I think we might get as a macro in the future. (As part of a more fundamental macro meaning "modify this lhs in-place".)

* `^` is visually appealing if you come at it from a logic notation perspective. (It kind of looks like [∧](https://en.wikipedia.org/wiki/Logical_conjunction), as in "this array *and* that array".) But... I fear it has too much baggage, and Perl 6 and Python basically tear it in twain, semantically. Perl 5 and Python have it as "bitwise xor", an operator I don't see us needing anytime soon. Perl 6 has it as the `one()` junction. What both Perl/Python agree on is that this operator means "this *xor* that", which kind of clobbers the nice visual resemblance to ∧.

Still suggesting with go with `concat(array1, array2)`, which isn't trying to be clever but just gets to the point immediately. Not everything can be an operator. ☺

**Comment by sergot** [comment]
Oh, wait, I missed the "array" word there, don't know why, I'm sorry :)

Let's stay with concat(a, b) then.

**Comment by vendethiel** [comment]
sure, fair :)

**Comment by andreoss** [comment]
Regarding https://github.com/masak/007/pull/104
May `concat()` be a variadic function? 
So one could write `concat(a, b, c)` instead of `concat(a, concat(b, c))`.

**Comment by masak** [comment]
I would recommend making it a two-argument function. It's nice if the built-ins work the same as the user defined functions, and there's no core Q support for variadic parameters.

My hope/dream is that optional/variadic parameters, and parameter defaults, could be provided through an importable language extension.

**Comment by masak** [comment]
Coming back to this discussion much later, it now seems self-evident to me that concatenation does not really need its own operator, but can instead be spelled `[...a1, ...a2]`. :smile:
