### ISSUE TITLE
Unreasonable assumption made in infix:<==>

### ISSUE THREAD

**Issue by masak** [masak/007#59]
$ perl6 bin/007 -e='say(Q::Literal::None() == 0)'
    Cannot call equal-value(Q::Literal::None, Val::Int); none of these signatures match:
        (Val, Val)
        (Val::None, Val::None)
        (Val::Int $l, Val::Int $r)
        (Val::Str $l, Val::Str $r)
        (Val::Array $l, Val::Array $r)
        (Val::Block $l, Val::Block $r)
        (Q $l, Q $r)
        (@l, @r)
        (Str $l, Str $r)

The assumption being that the two things being compared are of similar-enough types. (Like, at least two `Val` things, or two `Q` things.)

I suspect fixing this is as simple as replacing the `(Q, Q)` and `(Val, Val)` candidates with a single catch-all candidate. But I'm in the middle of a big refactor right now, so I don't want to investigate it at the moment.

**Comment by sergot** [comment]
fixed

**Comment by vendethiel** [comment]
:+1:
