### ISSUE TITLE
Unify Q::Statement::Sub and Q::Statement::Macro

### ISSUE THREAD

**Issue by masak** [masak/007#60]
I keep changing `Q::Statement::Sub` and `Q::Statement::Macro` in exactly the same ways all the time. They feel a bit like almost-duplicates of each other. Let's see:

* They're both routine declarators (our only two, at least before sub expressions)
* They're parsed identically, save for the keyword
* Their *action methods* are identical, save for the `Val` type they construct/make
* They both have an identifier and a block
* They're both invoked by passing a list of arguments to them
* They're both connected with a call frame
* They both produce a kind of `Val::Sub` (although `Val::Macro` is derived) which, when invoked, sets up a subhandler
* They both participate in the declaration of operators, which modifies the parser

It's a bit too much repetition. As to parser/actions, I definitely want to remove the duplication. With the two `Q` types, I'm less sure &mdash; mostly because I can see people wanting to search for `Q::Statement::Sub` and not get macros.

Is that a strong enough argument? I remember discussing with moritz++ at some point whether `Sub.ACCEPTS(Macro)` should be `True` in Perl 6. I argued "no" (and it currently returns `False`) because I feel that subs and macros are both routines, but one is not a subtype of the other. The same argument could be applied to `Q::Statement::Sub` and `Q::Statement::Macro` &mdash; they're more like siblings than in an inheriting relation.

Then again, their class bodies are *identical*. If it were still the 90s, I would inherit the crap out of those two! In 2015, I'm not so sure. Things can be identical but not related. There's no-one clamoring for making `Q::Statement::If`, `Q::Statement::For` and `Q::Statement::While` inherit from each other, even though they all represent control structures and all have the same attributes.

**Comment by vendethiel** [comment]
I don't have a comp right there, so I can't go check the implem. I agree with the "match subs but not macros problem", and I'm not sure I'd merge them as well, but we already had disagreements on whether operator application should coult as a sub or not previously...

Ps: **their** action methods

**Comment by masak** [comment]
> Ps: **their** action methods

Urgh -- fixed; thanks.

**Comment by masak** [comment]
As part of this, we might also want to merge the two test files `t/features/subs.t` and `t/features/macros.t`, and possibly check for cross-pollination between the two.
