### ISSUE TITLE
Make the linter able to reason about macro usages

### ISSUE THREAD

**Issue by masak** [masak/007#64]
This is a funny one. I had already coded up the linter code for "defined a sub, then didn't use it". I figured I could just copy the same test code into a separate one for macros, and change things around a little, and then implement it for macros.

But no. I can't do that. See, macro calls *aren't there* when the linter gets to the Qtree.

😂😂😂

I've since come up with three possible solutions:

* The linter gets a parser and calls it, getting a Qtree back. We could **inject the linter** into the parser, following some kind of `MacroUsageRecorder` interface. The parser could then feed information back to the linter through this private channel whenever a macro was expanded.
* **Annotate the Qtree** at the places where something was injected. Have a `.reduce` or `.deflate` method or some other opposite of "expand", which gives back the original Qfragment, the one with the macro call in it. (This could go on for several steps, for example if one of the arguments was also a macro call, or if the macro call was recursive. Maybe there also needs to be a method that goes all the way?)
* Have the parser provide a **trash heap** of Qfragments that didn't make it into the program Qtree, because they were replaced by the results of macro calls.

I think the first solution wins on simplicity and immediacy. It will probably be quite quick to implement.

The second solution, however, holds promise. It may be useful for other things, too. I'm thinking for example of good error messages &mdash; we should probably show the error message both in the generated code and in the original.

**Comment by masak** [comment]
A fourth possibility:

* Parse the file, but **don't expand the macros**.

I initially rejected this as not a viable option, but it's just a matter of parsing in a certain `:macro-noexpand` mode, I guess.

This is the simplest solution, to the extent that it will work. Also, we might need it for *other* stuff, for example the refactoring bit. (How do you inline a macro call you can't even see?)

But... I feel apprehension about this solution, too. We're going to make macros powerful and (opt-in) unhygienic. Can this be at all squared with not expanding the macros? I feel we're quickly heading into PPI territory here. Taken to its logical conclusion, the question seems to be: how good a job can a static code analyzer do steering between

1. seeing macros in their unexpanded form,
2. taking unhygienic effects of macros into account downstream of macro calls, and
3. avoiding the halting problem?

**Comment by vendethiel** [comment]
This is probably a good idea. Note that, if the macro introduces an operator or something, you can't parse the file. That's the main issue. Maybe just a "dumb" regexp to do this is the best option.

I know Clojure's IntelliJ plugin (Cursive) is extensible enough that you can add "rules" for each macros, to tell the IDE what it'll expand to (thus enabling completion of macro-generated forms)

**Comment by masak** [comment]
After spending a few more cycles on this, I think solution two (annotate the tree) and solution four (don't expand the macros) should be combined: parse the program normally, including macro expansions. Have a way to traverse the tree and do `.reduce` everywhere so that the Qtree closest to the actual program results.

So the macros do get expanded, but we only care about the expansions in order to make the parse equivalent to a normal one for running a program. Unhygienic macros can still do their thing. The halting problem is still a problem, but no more than for ordinary compilation of macros. (Heuristics and "this is ridiculous"-type timeouts can probably mostly solve problems of non-halting.)

**Comment by masak** [comment]
Here's yet another use case: displaying the Qtree of a certain bit of source code on the home page, as detailed in #67. Displying the *expanded result* would kind of defeat the intended goal of showing how macro calls look as Qtrees.

It's becoming increasingly clear that there are a number of consumers &mdash; linters, refactoring tools, code analysis tools, the above Qtree-displaying case &mdash; that want to view the source code *qua* source code, and isn't (yet) interested it the expanded result. Tools which aim to *run* the source without reflecting on its original form are much more likely to want the expanded version. A worthy distinction to make.

**Comment by masak** [comment]
Coming back with slightly fresh eyes in this issue, I'm thinking this:

* It's no trouble just building two Qtrees in parallel:
    * One the usual, with everything expanded
    * One when asked for it, with nothing expanded
* If there are compile-time side effects happening, they would still happen on the first, usual Qtree
* The second un-expanded Qtree would only be built if an opt-in flag was passed in to the parser (`:unexpanded`, say)
