### ISSUE TITLE
Implement comments

### ISSUE THREAD

**Issue by masak** [masak/007#69]
Anywhere we allow whitespace. Same as Perl and Python: starts with an [octothorpe](https://en.wikipedia.org/wiki/Number_sign#Other_names_in_English) (`#`) and goes on until the end of the line.

    say("hello, world!");    # as seen in K&R

**Comment by andreoss** [comment]
Should comments be a part of the grammar? Or we can remove them before parsing starts?

**Comment by masak** [comment]
The prevailing approach in Perl 6 grammars is to override the ws rule. I think we could follow that approach. (But I also think the grammar is not ready for it and needs adapting a little bit.)

I don't think comments should be a Q type. They don't have any semantics.
