### ISSUE TITLE
Implement 'else'

### ISSUE THREAD

**Issue by masak** [masak/007#79]
As in, extend `Q::Statement::If` to have an `$.else` which can optionally contain a block. Extend the parsing rule correspondingly.

What about `elsif`, or `elif`, or whatever the love child of Perl and Python is supposed to call that construct? I find that the simplest thing to defend, design-wise, is to also allow `$.else` to contain another `if` statement. (See [discussion here](http://irclog.perlgeek.de/perl6/2015-11-09#i_11505403).)

I've found a few cases already in writing examples where having `else` would lead to clearer, more readable code. The only reason we've been able to do without it for so long is that it's never *strictly* necessary.

Some people reason that `else` is a "code smell". That may be so, but I see no reason to ax-grind that into the language design, thereby making it harder for people to refactor into and out of `else` constructs.

**Comment by vendethiel** [comment]
Is there something wrong with correct associativity + "else if" falling naturally?

Oh, actually if I think about it, we love our `{}`

**Comment by masak** [comment]
Cheating in the way I think you're implying, we'd accidentally introduce a scope around the `else if` clause. [Moritz pointed out](http://irclog.perlgeek.de/perl6/2015-11-09#i_11505406) that doesn't give the right behavior when a variable is declared in the `else if` expression. (Something that can't happen in 007, but it's still a good point.)

**Comment by masak** [comment]
Thanks to @andreoss++ work in f85941e6f78032d1800a3171d011fe3d7fe615af and e7464515f52a28127045e8238099eb70a1d47044, we now have this feature. Closing.
