### ISSUE TITLE
Methods are currently blocks; should be subs

### ISSUE THREAD

**Issue by masak** [masak/007#90]
This is right:

    $ perl6 bin/007 -e='sub foo() {}; say(foo)'
    <sub foo()>

This is currently wrong:

    $ perl6 bin/007 -e='my o = { foo() {} }; say(o.foo)'
    <block ()>

Goal: to make it print the same: `<sub foo()>`.

* In order for the method to be a sub, we'd need [sub expressions](https://github.com/masak/007/issues/66).
* Secondly, the name `foo` needs to automatically be installed in the sub expression, not just the property key.

**Comment by vendethiel** [comment]
FWIW, the reason I didn't go for that is because sub checked its name lexically (iirc)

**Comment by masak** [comment]
> FWIW, the reason I didn't go for that is because sub checked its name lexically (iirc)

Oh, very much. Putting `Q::Statement::Sub` in that slot would make zero sense. `Q::Block` is at least defensible, because although it isn't an expression as such, it at least has an `.eval` method.
